#!/bin/sh

bspc monitor DP-2 -d 1
bspc monitor HDMI-0 -d 2 3 4 5 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 0

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

bspc config focused_border_color "#00AAFF"

bspc rule -a FLOATING state=floating